---
# master control
- hosts: all
  roles:
  - role: common

- hosts: ntpmaster
  roles:
  - role: ntpmaster

- hosts: ntpslave
  roles:
  - role: ntpslave

- hosts: cdh
  roles:
  - role: cdh

- hosts: cm
  roles:
  - role: cm