---
# Task file for cm
-   name: "cm :: install cloudera manager packages"
    yum:
        name: "{{ packages }}"
    vars:
        packages:
        - "cloudera-manager-daemons"
        - "cloudera-manager-agent"
        - "cloudera-manager-server"
    register: cm

-   name: "cm :: enable auto-TLS"
    command: "sudo JAVA_HOME=/usr/java/jdk1.8.0_181-cloudera /opt/cloudera/cm-agent/bin/certmanager setup --configure-services"
    when: cm.changed